export const PAGES = {
    ADVERTISEMENT:              'PAGE/ADVERTISEMENT',
    BULLETBOARD_GIVEAWAY_SELL:  'PAGE/BULLETBOARD_GIVEAWAY_SELL',
    BULLETBOARD_BUY_NEED:       'PAGE/BULLETBOARD_BUY_NEED',
    BULLETBOARD_EVENTS:         'PAGE/BULLETBOARD_EVENTS',
    BULLETBOARD_RECRUITMENT:    'PAGE/BULLETBOARD_RECRUITMENT',
    BULLETBOARD_LIFE:           'PAGE/BULLETBOARD_RECRUITMENT',
    TOWN_GUIDE:                 'PAGE/TOWN_GUIDE',
    ABOUT_COMPANY:              'PAGE/ABOUT_COMPANY',
    ABOUT_CONTACT:              'PAGE/ABOUT_CONTACT',
    ABOUT_SITEPOLICY:           'PAGE/ABOUT_SITE_POLICY',
    ABOUT_ADVERTISEMENT:        'PAGE/ABOUT_ADVERTISEMENT'
}
