export const PAGES = {
    ADVERTISEMENT:              'PAGE/ADVERTISEMENT',
    BULLETINBOARD_GIVEAWAY_SELL:  'PAGE/BULLETINBOARD_GIVEAWAY_SELL',
    BULLETINBOARD_BUY_NEED:       'PAGE/BULLETINBOARD_BUY_NEED',
    BULLETINBOARD_EVENTS:         'PAGE/BULLETINBOARD_EVENTS',
    BULLETINBOARD_RECRUITMENT:    'PAGE/BULLETINBOARD_RECRUITMENT',
    BULLETINBOARD_LIFE:           'PAGE/BULLETINBOARD_LIFE',
    TOWN_GUIDE:                 'PAGE/TOWN_GUIDE',
    ABOUT_COMPANY:              'PAGE/ABOUT_COMPANY',
    ABOUT_CONTACT:              'PAGE/ABOUT_CONTACT',
    ABOUT_SITEPOLICY:           'PAGE/ABOUT_SITE_POLICY',
    ABOUT_ADVERTISEMENT:        'PAGE/ABOUT_ADVERTISEMENT'
}
